/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Administrator
 */
public class QuanLiSanPham extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiSanPham
     */
    public QuanLiSanPham() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        textID = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cbxSole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxBrand = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxCategory = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxSize = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbxColor = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        spinBH = new javax.swing.JSpinner();
        textPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textNote = new javax.swing.JTextArea();
        textName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spinAmount = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnCategory = new javax.swing.JButton();
        btnColor = new javax.swing.JButton();
        btnSize = new javax.swing.JButton();
        btnBrand = new javax.swing.JButton();
        btnSole = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton10.setText("Xóa hình");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(550, 110, 100, 25);

        jButton9.setText("NEW");
        getContentPane().add(jButton9);
        jButton9.setBounds(270, 355, 75, 33);

        jButton8.setText("San PhamHien Tai");
        getContentPane().add(jButton8);
        jButton8.setBounds(50, 460, 140, 30);
        getContentPane().add(textID);
        textID.setBounds(155, 98, 210, 16);

        jButton7.setText("San Pham Da Xoa");
        getContentPane().add(jButton7);
        jButton7.setBounds(50, 500, 141, 25);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(500, 500, 192, 20);

        jButton6.setText("UPDATE");
        getContentPane().add(jButton6);
        jButton6.setBounds(150, 359, 75, 25);

        jButton1.setText("SEACH");
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 500, 69, 20);

        jButton5.setText("ADD");
        getContentPane().add(jButton5);
        jButton5.setBounds(41, 359, 71, 25);

        cbxSole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxSole);
        cbxSole.setBounds(150, 290, 221, 22);

        jLabel3.setText("Color  ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(71, 172, 54, 16);

        jLabel8.setText("Sole: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 290, 40, 16);

        cbxBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxBrand);
        cbxBrand.setBounds(150, 250, 221, 22);

        jLabel7.setText("Category: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(71, 134, 72, 16);

        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxCategory);
        cbxCategory.setBounds(155, 131, 216, 22);

        jLabel6.setText("Brand");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 250, 43, 16);

        cbxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxSize);
        cbxSize.setBounds(151, 210, 220, 22);

        jLabel4.setText("Size: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(71, 213, 46, 16);

        cbxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxColor);
        cbxColor.setBounds(151, 169, 220, 22);

        jLabel13.setText("Amount");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(530, 300, 57, 16);

        jButton16.setText("DELETE");
        getContentPane().add(jButton16);
        jButton16.setBounds(393, 359, 71, 25);

        spinBH.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinBH);
        spinBH.setBounds(630, 320, 197, 22);
        getContentPane().add(textPrice);
        textPrice.setBounds(630, 250, 198, 22);

        jLabel11.setText("Pice ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 250, 57, 16);

        textNote.setColumns(20);
        textNote.setRows(5);
        jScrollPane2.setViewportView(textNote);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(630, 390, 198, 70);
        getContentPane().add(textName);
        textName.setBounds(630, 210, 198, 22);

        jLabel5.setText("B?o hành (tháng)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 330, 98, 14);

        jLabel2.setText("Id: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(71, 98, 30, 16);

        jLabel9.setText("ProductName: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(530, 210, 80, 16);

        spinAmount.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinAmount);
        spinAmount.setBounds(630, 290, 197, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quan Ly San Pham ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(335, 13, 216, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 540, 790, 253);

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setForeground(new java.awt.Color(255, 51, 102));
        jLabel15.setText("?nh");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(690, 30, 137, 155);

        jLabel14.setText("Decription: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 390, 61, 16);

        btnCategory.setText("+");
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategory);
        btnCategory.setBounds(389, 130, 41, 25);

        btnColor.setText("+");
        getContentPane().add(btnColor);
        btnColor.setBounds(389, 168, 41, 25);

        btnSize.setText("+");
        getContentPane().add(btnSize);
        btnSize.setBounds(389, 209, 41, 25);

        btnBrand.setText("+");
        getContentPane().add(btnBrand);
        btnBrand.setBounds(390, 250, 41, 25);

        btnSole.setText("+");
        getContentPane().add(btnSole);
        btnSole.setBounds(390, 290, 41, 25);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên", "Ngày sinh" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(410, 500, 71, 20);

        jButton12.setText("Ch?n hình");
        getContentPane().add(jButton12);
        jButton12.setBounds(550, 80, 100, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnSize;
    private javax.swing.JButton btnSole;
    private javax.swing.JComboBox<String> cbxBrand;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxColor;
    private javax.swing.JComboBox<String> cbxSize;
    private javax.swing.JComboBox<String> cbxSole;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JSpinner spinAmount;
    private javax.swing.JSpinner spinBH;
    private javax.swing.JLabel textID;
    private javax.swing.JTextField textName;
    private javax.swing.JTextArea textNote;
    private javax.swing.JTextField textPrice;
    // End of variables declaration//GEN-END:variables
}
